const dates = [
  {
    "id": 483,
    "created_at": "2019-10-18 22:51:39",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "TROPHIES",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 1,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Trophy",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "TROF\u00c9US",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 509,
    "created_at": "2019-10-19 10:06:23",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Trophy TROPHIES",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/e9WmE16QunIW7KrtG5WfmhHta43dp0pWTwzAkC8W.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 1,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Trof\u00e9u / Trof\u00e9us",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 484,
    "created_at": "2019-10-18 22:55:08",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "OFFICES",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 2,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Office",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "ESCRIT\u00d3RIOS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 510,
    "created_at": "2019-10-19 10:07:31",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Office OFFICES",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/RBTvM4qgEg3DjVbwxTnVK7vF7iE7B1rwAfMc0tMW.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 2,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "ESCRIT\u00d3RIO / ESCRIT\u00d3RIOS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 485,
    "created_at": "2019-10-18 22:56:09",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "SURVEYS",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 3,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Survey",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "PESQUISAS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 511,
    "created_at": "2019-10-19 10:09:10",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Survey SURVEYS",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/7LVa2zIAjzxlwxHPg6VkowjLU9Cf2hap3KSjYuhG.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 3,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Pesquisa / PESQUISAS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 512,
    "created_at": "2019-10-19 10:10:13",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Lady LADIES",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/hk9myi7MdHnZVME3caanzb8u2EGzrmE3x0Rhyiqk.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 4,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Senhora /  SENHORAS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 486,
    "created_at": "2019-10-18 22:56:59",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "LADIES",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 4,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Lady",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "SENHORAS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 513,
    "created_at": "2019-10-19 10:11:04",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Kiss KISSES",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/a5fhnreF0uu34jg0f9lQ8LAKeI0fz0aoCpNtsaXA.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 5,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Beijo / BEIJOS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 487,
    "created_at": "2019-10-18 22:57:41",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "KISSES",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 5,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Kiss",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "BEIJOS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 514,
    "created_at": "2019-10-19 10:12:25",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Tornado TORNADOES",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/eO2OgN6yVwPkQ6NVZJrx7Hj2YTK1BxBy5BnPzWfc.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 6,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Tornado / TORNADOS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 489,
    "created_at": "2019-10-18 23:03:35",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "TORNADOES",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 6,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Tornado",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "TORNADOS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 515,
    "created_at": "2019-10-19 10:13:46",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Tattoo TATTOOS",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/6EWFJNkNkPi4AukbOeCJlEIHTrKf7s06kTtld6fS.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 7,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Tatuagem / TATUAGENS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 490,
    "created_at": "2019-10-18 23:04:25",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "TATTOOS",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 7,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Tattoo",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "TATUAGENS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 516,
    "created_at": "2019-10-19 10:14:46",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Wish WISHES",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/mNWepmE0YT4Voy3NIzffhI23hawkrQl18LclvdKR.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 8,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Desejo / DESEJOS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 491,
    "created_at": "2019-10-18 23:07:07",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "WISHES",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 8,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Wish",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "DESEJOS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 517,
    "created_at": "2019-10-19 10:15:57",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Life LIVES",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/k9rmnVmbCCrXpX6jVnFwRHV7H7NuYswj4gH8dXVs.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 9,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Vida / VIDAS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 492,
    "created_at": "2019-10-18 23:08:23",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "LIVES",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 9,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Life",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "VIDAS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 518,
    "created_at": "2019-10-19 10:17:30",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Shampoo SHAMPOOS",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/SHZxbMuVV6xeBOEzuFBIRoSTmk4TPT6OEJc4z35l.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 10,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": null,
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 493,
    "created_at": "2019-10-18 23:09:10",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "SHAMPOOS",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 10,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Shampoo",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "SHAMPOOS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 519,
    "created_at": "2019-10-19 10:18:23",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Lunch LUNCHES",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/SfO0vaxP3AWd6FX55I1PVtjE9EgR3NOSiHxHjjL3.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 11,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Almo\u00e7o / ALMO\u00c7OS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 494,
    "created_at": "2019-10-18 23:09:57",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "LUNCHES",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 11,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Lunch",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "ALMO\u00c7OS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 520,
    "created_at": "2019-10-19 10:19:21",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Knife KNIVES",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/6UJUS8HzeYdvILehGRJkGY69zXcpQPhtZCxTqay3.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 12,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Faca / FACAS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 495,
    "created_at": "2019-10-18 23:10:44",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "KNIVES",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 12,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Knife",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "FACAS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 521,
    "created_at": "2019-10-19 10:20:23",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Tomato TOMATOES",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/cB6LXAIs7OCK66Wq8sQtL31Ve7yWVbJffuXgAxS8.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 13,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Tomate / TOMATES",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 496,
    "created_at": "2019-10-18 23:12:20",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "TOMATOES",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 13,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Tomato",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "TOMATES",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 522,
    "created_at": "2019-10-19 10:21:11",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Child CHILDREN",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/nYxtjXsJXgtQ5JgjzzBRVDG4kqcbm5ZrL8Jak1Ch.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 14,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Crian\u00e7a / CRIAN\u00c7AS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 497,
    "created_at": "2019-10-18 23:13:05",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "CHILDREN",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 14,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Child",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "CRIAN\u00c7AS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 523,
    "created_at": "2019-10-19 10:22:26",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Candy CANDIES",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/rl1FarUPwt5DyJ7e9x0eFOC7kYbXmcOzGu8Z5bDe.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 15,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Doce / DOCES",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 498,
    "created_at": "2019-10-18 23:13:51",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "CANDIES",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 15,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Candy",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "DOCES",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 524,
    "created_at": "2019-10-19 10:23:42",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Hero HEROES",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/0uRDRoWKOoDAYFOS7Xxb4CUftKZf0oeAAypKo4Zq.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 16,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Her\u00f3i / HER\u00d3IS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 499,
    "created_at": "2019-10-19 09:54:36",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "HEROES",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 16,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Hero",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "HER\u00d3IS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 525,
    "created_at": "2019-10-19 10:24:59",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Piano PIANOS",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/WJv1bhM6UQCpRe9GcLZc3OXYPmC6ftY1UabxUby6.mp3",
    "a": "Piano PIANO'S",
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 17,
    "subtitle": "",
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Piano / PIANOS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 500,
    "created_at": "2019-10-19 09:55:25",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "PIANOS",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 17,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Piano",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "PIANOS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 526,
    "created_at": "2019-10-19 10:26:08",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Loaf LOAVES",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/tfu5oOocaBMByJBIzK0Yci1RQgMgvJIPNptBrt79.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 18,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "P\u00e3o / P\u00c3ES",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 501,
    "created_at": "2019-10-19 09:57:00",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "LOAVES",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 18,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Loaf",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "P\u00c3ES",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 527,
    "created_at": "2019-10-19 10:26:57",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Box BOXES",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/Qa2JdQlBJKmYfcHi3wTnplqLD3YUD1PoB5UkMYxy.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 19,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Caixa / CAIXAS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 502,
    "created_at": "2019-10-19 09:57:46",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "BOXES",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 19,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Box",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "CAIXAS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 528,
    "created_at": "2019-10-19 10:28:10",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Spy SPIES",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/F1zTRUzl1PSwgIPapjnw7FQmGTT0t7aP1AuX2BKp.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 20,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Espi\u00e3o / ESPI\u00d5ES",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 503,
    "created_at": "2019-10-19 09:59:48",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "SPIES",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 20,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Spy",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "ESPI\u00d5ES",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 529,
    "created_at": "2019-10-19 10:29:06",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Woman WOMEN",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/W1HQnZ0Gs08ya6eFRUcQEpI1Lmio5dvjFWUDpOzO.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 21,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Mulher / MULHERES",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 504,
    "created_at": "2019-10-19 10:00:43",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "WOMEN",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 21,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Woman",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "MULHERES",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 530,
    "created_at": "2019-10-19 10:29:55",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "River RIVERS",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/K400b9Uv3pY1cmchdQl4SsJ26HM78yPx0zSHKeI5.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 22,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Rio / RIOS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 505,
    "created_at": "2019-10-19 10:02:08",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "RIVERS",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 22,
    "subtitle": null,
    "sub_type": "complete",
    "start": "River",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "RIOS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 531,
    "created_at": "2019-10-19 10:30:58",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Baby BABIES",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/1omyDNDUc7o03FvIWvgaLZuhf9GjZnQpTcZSRH0m.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 23,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Beb\u00ea / BEB\u00caS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 506,
    "created_at": "2019-10-19 10:02:59",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "BABIES",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 23,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Baby",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "BEB\u00caS",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 532,
    "created_at": "2019-10-19 10:31:56",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Sandwich SANDWICHES",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/JKgxtNbdk9wlDLY0TXXsvX9cecSlAGvwYwTscgcK.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 24,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Sandu\u00edches / SANDU\u00cdCHES",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 507,
    "created_at": "2019-10-19 10:03:54",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "SANDWICHES",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 24,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Sandwich",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "SANDU\u00cdCHES",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 533,
    "created_at": "2019-10-19 10:33:32",
    "title": "REPITA A FRASE",
    "type": "fonetico",
    "answer": "Boy BOYS",
    "lesson_id": 27,
    "audio": "https://profkenny3.s3.us-east-2.amazonaws.com/AA5jHbe95VXVZ8OfVHZDmAABMdueLRvR6MZuXAxw.mp3",
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 25,
    "subtitle": null,
    "sub_type": "alternativas",
    "start": null,
    "end": null,
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "Rapaz / RAPAZES",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  },
  {
    "id": 508,
    "created_at": "2019-10-19 10:04:53",
    "title": "COLOQUE NO PLURAL",
    "type": "gramatico",
    "answer": "BOYS",
    "lesson_id": 27,
    "audio": null,
    "a": null,
    "b": null,
    "c": null,
    "d": null,
    "e": null,
    "size": 4,
    "order": 25,
    "subtitle": null,
    "sub_type": "complete",
    "start": "Boy",
    "end": ".",
    "a_answer": null,
    "b_answer": null,
    "c_answer": null,
    "d_answer": null,
    "e_answer": null,
    "phrase": null,
    "translate": "RAPAZES",
    "img": null,
    "f": null,
    "g": null,
    "h": null,
    "i": null,
    "j": null,
    "f_answer": null,
    "g_answer": null,
    "h_answer": null,
    "i_answer": null,
    "j_answer": null
  }
];

export default dates;